language: csharp
solution: backend/backend.sln
mono: none
dist: xenial
dotnet: 2.2
sudo: false
script:
  - dotnet restore backend/backend.sln
  - dotnet build backend/backend.sln
  - dotnet test backend/backend.Tests/backend.Tests.csproj
  